### ISSUE TITLE
weergave van routes niet optimaal

### ISSUE THREAD

**Issue by ndkv** [ndkv/vm#103]

**Comment by ndkv** [comment]
@Ftmeijer Zal ik grafisch ontwerp volgen hierin? 

Wat doen we met expedities die geen routes hebben? Weegave met vierkantjes goed? 

Wat doen we met evt. overlappende vierkanten? En expedities die PoI over de hele wereld hebben?

**Comment by Ftmeijer** [comment]
Ik denk dat dit iets is waar iedereen zijn mening over miet geven. 
Wat ik goed vind aan het ontwerp is dat door het gebruik van de stippen, het er echt als een route uit ziet. Het suggereert daardoor ook meer klikbaar te zijn. Nu is het klikken op de routes lastig. 

Het hoeven van mij niet de daadwerkelijke poi’s te zijn. Het mag een lijn zijn met een aantal poi stippen er in geintegreerd oid. 


De weergave met vierkantjes is prima. Maar dat mag dus ook een lijn zijn met (fictieve) poi stippen er in. 
Wat betreft expedties over de hele wereld verspreid. Ik denk dat wij een redactionele keus moeten laten maken waar het zwaartepunt ligt. En daar dan ook een vierkant voor gebruiken. 

Is dat iets?


-----------------------------------------------
Frank Meijer
Stichting Academisch Erfgoed
Projectleider
f.t.meijer@academischerfgoed.nl <mailto:f.t.meijer@academischerfgoed.nl> 
06-11060137

www.academischerfgoed.nl <http://www.academischerfgoed.nl/> 
www.academischecollecties.nl <http://www.academischecollecties.nl/>

**Comment by ndkv** [comment]
Goed.

Ik volg grafisch ontwerp.

**Comment by memunnik** [comment]
Is het mogelijk om op uitgezoomd niveau 1 grotere stip te zien in geval van een locale expeditie...en als je inzoomt dat je dan de route of meerdere POI's  te zien krijgt. Ik persoonlijk vind het rode vierkantje niet mooi passen in het design. 

Verspreide POI's over de wereld in geval van bijv. VOC expedities kijken.....kan je ook niet echt een lijn trekken... ik denk dat de lijn verwarrend werkt....wellicht de kleur van de samenhangende stippen aanpassen indien deze wordt aangeklikt of in het expeditiemenu wordt aangeklikt.

Geactiveerde kleur is ... zwart
Gedeactiveerde kleur is ... wit....

**Comment by ndkv** [comment]
Rode stippelijn en vierkanten zijn vervangen door zwarte lijn en zwarte vierkanten.

**Comment by memunnik** [comment]
Ziet er netjes uit, waarbij ik pleit voor rond ipv vierkant...vanuit design perspectief sluit dat beter aan met de rest van de POI's!!!

Dus semi transparant zwart met zwarte cirkel (dus zonder stip in het midden), en dan even groot als de vierkanten....

**Comment by ndkv** [comment]
Goed punt, kijk er z.s.m. naar.
