### ISSUE TITLE
implementeer mogelijkheid om lokale afbeeldingen in PoI scherm te laden

### ISSUE THREAD

**Issue by ndkv** [ndkv/vm#113]
Niet alle afbeeldingen kunnen naar Commons geupload worden. 

Op dit moment kunnen enkel afbeeldingen uit Commons getoond worden in app

**Comment by Ftmeijer** [comment]
Er zitten in de poi's van de VM expeditie toch ook al plaatjes die niet uit commons komen? Of werkt dat anders?

**Comment by ndkv** [comment]
Dit is af, zie laatste paar PoIs in Ceram expeditie. 

Ik heb plaatjes naar jpeg geconverteerd, browsers kunnen geen tiff tonen.
