### ISSUE TITLE
Openen POI VM werken niet in een keer allemaal goed

### ISSUE THREAD

**Issue by memunnik** [ndkv/vm#127]
Als ik sommige POI's van VM open, dan krijg ik eerst een leeg scherm. Vervolgens sluit ik hem en klik vervolgens weer op de POI (lees meer) en dan komt de tekst en beeld wel zichtbaar..... ??!!

**Comment by ndkv** [comment]
Zijn het steeds dezelfde PoIs?

**Comment by ndkv** [comment]
Gefixt (denk ik), komt het nog voor bij jou?

**Comment by memunnik** [comment]
Ik zie nu helemaal geen tekst meer bij de uitgeklapte POI VM… ☹

**Comment by ndkv** [comment]
Ze doen het weer, omzetten naar /#vening-meinesz was  niet helemaal goed gegaan.
