### ISSUE TITLE
In en uitklappen menubalk met expedities werkt niet goed

### ISSUE THREAD

**Issue by memunnik** [ndkv/vm#140]
Dicht klappen lukt, maar open klappen niet. ipv de menu weer te zien, zie je plots start expeditiescherm van een reis.
Of er de leesmeerknoppen zijn te zien met een lege achtergrond??

**Comment by memunnik** [comment]
er zit blijkbaar een frequentie in, want na een paar keer proberen zie je wel het overzicht van de expedities staan

**Comment by ndkv** [comment]
Ik kan dit niet reproduceren in IE 11 en Chrome... de expedities 
verschijnen weer, ook naa meerdre keer klikken.

**Comment by memunnik** [comment]
Chrome Version 41.0.2272.101 m  Dit is het resultaat van het open en dichtklappen van de menubalk kies een reis… vaak goed maar soms ook fout..nu opent hij start scherm  reis Nl in Ceram … openklap plusje op de balk mist hier ook

[cid:image001.png@01D06C7A.E0CC4E00]

**Comment by memunnik** [comment]
Firefox Versie 36.0.4.  heel vaak (20 x achter elkaar) open en dichtklappen en hij schiet vanzelf scheef. Daarna nog een 20 x ging het wel goed…vage klacht….

[cid:image001.png@01D06C7B.A10E23A0]
