### ISSUE TITLE
De POI cirkels van de VM expedities zijn nog steeds stuk

### ISSUE THREAD

**Issue by memunnik** [ndkv/vm#142]
Ik zie steeds van dei vierkantjes met kruisjes erin...error

IE browser 11

**Comment by memunnik** [comment]
Bij alle expedities is dit issue!

**Comment by ndkv** [comment]
Bij mij werkt dit goed in IE 11.

Weet je zeker dat je IE 11 gebruikt?

**Comment by ndkv** [comment]
Wederom, bij mij werkt het prima. Welke IE versie gebruik je?

**Comment by memunnik** [comment]
[cid:image001.png@01D06C78.214F12D0]

**Comment by memunnik** [comment]
Ik gebruik 10.0.9200.17267, dus het klopt dat ik dingen zie die jij niet ziet ivm versie

Misschien andere vraag…

Voor welke IE werkt het!? Alleen IE 11??

Wat is reëel? Vanaf welke versie uberhaupt, ook in relatie tot de andere browsers…

**Comment by ndkv** [comment]
Ik heb op het moment alleen 11.

Gevoelsmatig denk ik dat het redelijk makkelijk is om het ook op 10 
werkend te krijgen (want het gaat vooral mis in weergave van content, 
niet in functionaliteit) maar dat het veel moiete gaat kosten om lager 
te gaan.

Op welke versie zitten de TU PCs tegenwoordig? Zijn jullie al over op Win 7?

**Comment by ndkv** [comment]
Gefixt op apps.ndkv.nl/vm-dev Als het naar behoren werkt pas ik expeditiwikipedia.nl aan
