### ISSUE TITLE
kaart en inzoomprobleem: bruin blok verschijnt.

### ISSUE THREAD

**Issue by memunnik** [ndkv/vm#166]
Zie bij het inzoomen en uitzoomen soms van die vierkante blokken die aanwezig blijven, m.n. zuid-america is steeds de klos. Als je verder uitzoomt of inzoomt met scroll van je muis, gaat het weer weg. Zowel in IE11 als Chrome, dus het lijkt een algemeen kaart en inzoomprobleem

**Comment by ndkv** [comment]
Dit lijkt een defect in de kaart, een van de tegels is niet goed 
gegenereerd.

Klopt het dat het alleen op tweede zoomniveau het geval is?

Indien het geval dan moeten we iDelft een nieuwe kaart laten renderen.

**Comment by memunnik** [comment]
Het gebeurt tijdens in en uitzoomen. Je ziet hem steeds verschijnen en verdwijnen. Als je ergens halverwege plots stopt met scrollen lijkt deze soms te blijven staan op de kaart.

Dus inderdaad lijkt het op het 2de zoom niveau te liggen.

**Comment by ndkv** [comment]
Opgelost: tegel was niet goed naar server gekopieerd.
