### ISSUE TITLE
bestsellers expeditie heeft geen beshcrijving

### ISSUE THREAD

**Issue by ndkv** [ndkv/vm#179]

**Comment by Ftmeijer** [comment]
Die heeft volgens mij wel een beschrijving. 
Staat in het overzicht expedities. Dat is toch de goede plek?

---

Frank Meijer
Stichting Academisch Erfgoed
Projectleider
f.t.meijer@academischerfgoed.nl mailto:f.t.meijer@academischerfgoed.nl 
06-11060137

www.academischerfgoed.nl http://www.academischerfgoed.nl/ 
www.academischecollecties.nl http://www.academischecollecties.nl/

**Comment by ndkv** [comment]
Je hebt gelijk.
