### ISSUE TITLE
toon expeditie/poi tekst in witte balk nadat menu ingeklapt is

### ISSUE THREAD

**Issue by ndkv** [ndkv/vm#34]

**Comment by ndkv** [comment]
Frank stelt voor om menu uit te klappen als gebruiker op PoI klikt ipv expeditie/poi tekst in witte balk te tonen. 

Wat zullen we doen ?

**Comment by Ftmeijer** [comment]
Mijn opmerking was vooral ingegeven omdat er nu nog niks gebeurt. En mij was de oplossing met de witte balk niet duidelijk geworden uit het grafisch ontwerp,
We moeten ons vooral afvragen waarom iemand het menu inklapt.  Dat doe je waarschijnlijk om de kaart beter te kunnen zien. Als dan et menu steeds weer terugklapt is misschien ook wel irritant.

**Comment by ndkv** [comment]
Nu dat ik goed kijk zie ik dat er geen ontwerp is voor ingeklapte PoI menu, enkel voor ingeklapte expeditie menu. PoI menu op die manier verbergen is lastig want wat doe je met afbeeldingen,  'lees meer' knoppen en beschrijvingen die langer zijn dan breedte van scherm. 

Als je niet wilt dat menu uitklapt moet je niet op PoIs drukken, makkelijk te leren denk ik? 

**Voorstel**: menu uitklappen als gebruiker op PoI/route klikt. 

Aller-allermakkelijkste oplossing is om in/uitklappen van menu uit te zetten.

**Comment by Ftmeijer** [comment]
Ik persoonlijk vind de meerwaarde van het inklappen niet zo groot. Maar misschien is het op kleinere schermen toch wel prettig.
Wat mij betreft graag in te ruilen voor een van de issues op de backlog :-)

Lijkt me een punt waar we meer meningen over moeten horen.

**Comment by ndkv** [comment]
Goed. 

Dit lijkt me meer een punt voor Tremani; ik stuur ze een mail.

**Comment by ndkv** [comment]
Vandaag ontdekte ik dat inklappen fijn is als je tablet in landscape houdt.

**Comment by ndkv** [comment]
@memunnik Heb jij hier ideeen over?

**Comment by ndkv** [comment]
Zojuist aan de telefoon besproken dat beste oplossing is om balk uit te klappen als gebruiker op route of PoI klikt.

**Comment by Ftmeijer** [comment]
ok
-----------------------------------------------
Frank Meijer
Stichting Academisch Erfgoed
Projectleider
f.t.meijer@academischerfgoed.nl <mailto:f.t.meijer@academischerfgoed.nl> 
06-11060137

www.academischerfgoed.nl <http://www.academischerfgoed.nl/> 
www.academischecollecties.nl <http://www.academischecollecties.nl/>
