### ISSUE TITLE
historische kaarten kunnen niet aan/uitgezet worden in expeditiescherm

### ISSUE THREAD

**Issue by ndkv** [ndkv/vm#60]

**Comment by ndkv** [comment]
In PvE staat dat kaarten alleen in 'expeditie scherm' aan/uitgezet moet kunnen worden.

**Comment by Ftmeijer** [comment]
Ik bedoel hier op de eerste pagina, met het overzicht van expedities. Daar zouden volgend het grafisch ontwerp helemaal geen historische kaarten te zien zijn, maar alleen de expedities met korte teksten in de kaart. 
Als dan nu wel  van iedere expeditie de historische kaarten worden getoond, wil ik ze wel graag uit kunnen zetten.

**Comment by ndkv** [comment]
Hist. kaarten komen inderdaad niet voor in grafisch ontwerp, wel in PvE. 

Wat zal ik doen? Hist. kaarten vervangen door routes met tekst of laten staan en aan/uit control bouwen?

Kaarten weghalen lost #61 op, echter er zitten wat haken en ogen aan routes met tekst maken:
 - tekst in EN/NL schrijven voor labels
 - we moeten handmatig plaatsing van labels bepalen om o.a. overlap te voorkomen
 - hoe pakken we expedities aan die geen route hebben?
 - grafisch ontwerp oog mooi maar tekst is te klein -> het kan zijn dat routes met tekst in app niet mooi oogt. 

What to do?

**Comment by Ftmeijer** [comment]
Ik ben er op zich niet op tegen om de historische kaarten te laten zitten, mits ze aan en uit kunnen worden gezet.
Wel vind ik sowieso de manier om een route weer te geven nog niet optimaal. Maar dat zit volgens mij nog in een ander issue, toch?

PS: ik reply nu via de mail. Komt de opmerking dan wel in de issue tracker terecht?



-----------------------------------------------
Frank Meijer
Stichting Academisch Erfgoed
Projectleider
f.t.meijer@academischerfgoed.nl <mailto:f.t.meijer@academischerfgoed.nl> 
06-11060137

www.academischerfgoed.nl <http://www.academischerfgoed.nl/> 
www.academischecollecties.nl <http://www.academischecollecties.nl/>

**Comment by ndkv** [comment]
Goed, ik bouw een aan/uitzet control. 

Heb een nieuwe issue gemaakt voor routes: #103
Issue #61 gaat over combinatie van kaarten met routes. 

--

Yep, mails komen in issue tracker terecht, zie https://github.com/ndkv/vm/issues/60
