### ISSUE TITLE
Voor de intropagina een grote foto gebruiken, voorzien van een korte inleiding.

### ISSUE THREAD

**Issue by ndkv** [ndkv/vm#69]
Zoals in het grafisch ontwerp

**Comment by ndkv** [comment]
@ftmeijer Waar komt introtekst vandaan? OK om eerste 150-200 woordne van hoofdlemma te gebruiken?

**Comment by Ftmeijer** [comment]
Introtekst is niet meer dan een paar regels. Komt uit excel sheet.

**Comment by ndkv** [comment]
Ik heb weergave van introteksten en PoI teksten aangepast volgens grafisch ontwerp en bovenstaande. 

Er blijft weinig ruimte over voor de grote afbeelding over de breedte. We moeten een keus maken; huidig ontwerp of alleen grote afbeelding over de breedte. Beide (zoals in grafisch ontwerp) wordt lastig omdat een van de twee afbeelding te klein wordt. Indien we voor grote afbeelding kiezen is het de vraag hoe titel en beschrijving op te nemen. 
Titel kan ik zwarte balk bovenaan. Beschrijving wordt dan een regel boven de grote afbeelding. 

Wat zullen we doen? 

Persoonlijk vind ik de huidige opzet OK omdat je meer tekst kan laten zien.

**Comment by Ftmeijer** [comment]
Ik ben er voor om alleen de grote afbeelding te doen over de hele breedte, met titel in de zarte balk en beschrijving (regel) in de witte balk er boven. Dat komt ook omdat wij geen uitgebreide introductieverhalen hebben. En ik wil daar geen wikipedia artikel omdat je dan twee klik opties hebt, naar wikipedia en naar de expeditie. Is niet logisch. 

Als het nodg is om bijgesnede afbeeldingen voor aan te leveren is dat prima, en waarschijnlijk zelfs wenselijk. Dan kunnen we zelf een mooie uitsnede bepalen. 

Maar zoals gezegd, ik hoor graag wat de anderen hier van vinden. 




-----------------------------------------------
Frank Meijer
Stichting Academisch Erfgoed
Projectleider
f.t.meijer@academischerfgoed.nl <mailto:f.t.meijer@academischerfgoed.nl> 
06-11060137

www.academischerfgoed.nl <http://www.academischerfgoed.nl/> 
www.academischecollecties.nl <http://www.academischecollecties.nl/>

**Comment by ndkv** [comment]
Ik heb zojuist de intropagina aangepast. In portrait ziet het er prima uit, in landscape vind ik het iets te krap. Het kan zijn dat het meevalt als we plaatjes goed bijgesneden hebben i.e. dat er daadwerkelijk iets te zien is (nu zie je alleen lucht). 

Breedte van plaatje is nu gelijk aan breedte scherm. Op een iPad is dit 1024 (landscape) en 768 (portrait). De hoogte van de afbeelding is nu 320px, ik kan deze aanpassen. Zodra we een hoogte hebben bepaald kunnen we afbeeldingen bijsnijden, vraag is dus: hoe hoog willen we plaatje hebben?

**Comment by ndkv** [comment]
Alternatieve plaatsing van introtekst:

![vmontwerp](https://cloud.githubusercontent.com/assets/778666/6685883/40793006-cc9e-11e4-835a-af1c28fd5ac0.PNG)

**Comment by ndkv** [comment]
Iets mooiere versie met knoppen over grote afbeelding: 

![vmontwerp2](https://cloud.githubusercontent.com/assets/778666/6692721/aaf6675c-ccce-11e4-94f8-51ea440cf8bc.PNG)

**Comment by ndkv** [comment]
En nog een iteratie:

![vmontwerp3](https://cloud.githubusercontent.com/assets/778666/6697288/e0331778-ccef-11e4-9c0c-5ad7e640cdc8.PNG)

**Comment by memunnik** [comment]
Deze ontwikkeling vind ik prima

**Comment by ndkv** [comment]
VM, Ceram, Nieuw-Guinea en Bestsellers expedities hebben een eigen afbeelding. 

Afbeeldingen zijn een veelvoud van 768 x 440 (breedte x hoogte). Als scherm nauwer is dan 768 px (portrait stand iPad) dan knip ik het plaatje af. Als scherm breeder is dan 768 px dan 'zoom' ik het plaatje in. Als plaatje hoger wordt dan 650px dan begint ie uit te rekken. 

Ik kan het uitrekken uitzetten maar dan zoomen meeste plaatjes te veel in. 

Is het goed zo? 

@ftmeijer als je andere afbeeldingen wil aanleveren is dat prima. Zorg er wel voor dat ze bijgesnede worden in veelvoud van 768x440. Overigens kan ik hoogte instellen, breedte niet.

**Comment by Ftmeijer** [comment]
Ziet er goed uit. 
IK zorg in ieder geval dat de foto voor de siboga expeditie wordt aangeleverd. 

-----------------------------------------------
Frank Meijer
Stichting Academisch Erfgoed
Projectleider
f.t.meijer@academischerfgoed.nl <mailto:f.t.meijer@academischerfgoed.nl> 
06-11060137

www.academischerfgoed.nl <http://www.academischerfgoed.nl/> 
www.academischecollecties.nl <http://www.academischecollecties.nl/>

**Comment by Ftmeijer** [comment]
Ik heb alvast een nieuwe afbeelding voor de Siboga expesitie toegevoegd. Zie Excel en dropbox. Het plaatje van het schip wel graag laten staan bij het poi overzicht.


-----------------------------------------------
Frank Meijer
Stichting Academisch Erfgoed
Projectleider
f.t.meijer@academischerfgoed.nl <mailto:f.t.meijer@academischerfgoed.nl> 
06-11060137

www.academischerfgoed.nl <http://www.academischerfgoed.nl/> 
www.academischecollecties.nl <http://www.academischecollecties.nl/>

**Comment by ndkv** [comment]
Mooie afbeelding, hij zit erin!
