### ISSUE TITLE
pijltje om menu terug te scrollen ontbreekt

### ISSUE THREAD

**Issue by ndkv** [ndkv/vm#76]

**Comment by ndkv** [comment]
Beste oplossing is om het onder/boven bestaande pijltje te plaatsen.

**Comment by ndkv** [comment]
Zit overigens niet in grafisch ontwerp.

**Comment by Ftmeijer** [comment]
Nee, daar hebben we toch wel een beetje overheen gekeken. Hoe wil je anders terug scrollen op een gewone computer?

**Comment by ndkv** [comment]
Je kan ook op een PC 'swipen', werkt best goed op een Mac (fijne touchpad), minder op Win. 

Goed als ik pijltje om terug te scrollen boven/onder bestaande pijltje plaats? Dit lijkt mij de cleanste oplossing. 

Andere mogelijkheid is links van menu maar dan krijg je nog een strook met wit tussen beschrijving en menu.

**Comment by Ftmeijer** [comment]
Wat mij betreft wel
