### ISSUE TITLE
Offerte: navigatie van de app is bechikbaar in twee talen

### ISSUE THREAD

**Issue by ndkv** [ndkv/vm#96]

**Comment by ndkv** [comment]
Hangt af van https://waffle.io/ndkv/vm/cards/550093cc1279625f0021afb5 i.e. komen er beschrijvingen van elke expeditie in twee talen?

**Comment by Ftmeijer** [comment]
Even de definities helder krijgen: wat bedoel jij met een introtekst van een expeditie? De tekst die verschijnt als je op start expeditie klikt? 
Daar komt wat ons betreft vooral een grote afbeelding (uit dropbox) of commons + een korte intreoductietekst. Zoals in het grafisch ontwerp. 
In het overzicht expedities tabblad in de excellijst zie je de verwijzing naar de expeditieafbeelding en een veld voor een introtekst. Dat zal de ene keer een engelse, en de andere keer een nederlandse tekst zijn. Dus bepaald door de 'redactie' 

Zoals ik het in mijn hoofd heb  is de tweetaligheid alleen van toepassing op navigatie en eerste introtekst. Dus: in beide taalversies krijg je alle expedities te zien. 
Verder zouden de 'over deze app' pagina's ook tweetalig moeten worden denk ik.  Deze wil ik echt parkeren tot het eind. Zijn standaard platte pagina's.

**Comment by ndkv** [comment]
Met introtekst van expeditie bedoel ik stukje tekst die je ziet nadat je 
op een 'Lees meer' link op overzichtspagina klikt.

**Comment by Ftmeijer** [comment]
Ok. Dan bedoelen we hetzelfde. 
Een korte, door redactie gemaakte introtekst is volgens mij het beste. De eerste regels van de encyclopedische artikelen zijn hier niet altijd voor geschikt. 


-----------------------------------------------
Frank Meijer
Stichting Academisch Erfgoed
Projectleider
f.t.meijer@academischerfgoed.nl <mailto:f.t.meijer@academischerfgoed.nl> 
06-11060137

www.academischerfgoed.nl <http://www.academischerfgoed.nl/> 
www.academischecollecties.nl <http://www.academischecollecties.nl/>

**Comment by ndkv** [comment]
Heb een knop om taal te switchen opgenomen links van hoofdmenu. 

Taal switch kan ook als je 'Lees meer' scherm van een expeditie open hebt. 

Hoe laten we de gebruiker weten dat een expeditie eentalig is? 

Ik kan NL/EN achter Start expeditie! knop plaatsen als duiding.

**Comment by Ftmeijer** [comment]
KLopt het dat ik de taalswitch nog niet zie?

Ik zou de taal aanduiding achter de titel vermelden, en ook al in de scrollbalk. 

Vening Meinesz (EN)
Siboga Expeditie (NL) 



-----------------------------------------------
Frank Meijer
Stichting Academisch Erfgoed
Projectleider
f.t.meijer@academischerfgoed.nl <mailto:f.t.meijer@academischerfgoed.nl> 
06-11060137

www.academischerfgoed.nl <http://www.academischerfgoed.nl/> 
www.academischecollecties.nl <http://www.academischecollecties.nl/>

**Comment by ndkv** [comment]
Zie je iets in rechterbovenhoek? Links van hoofdmenu? 

On 16 March 2015 17:49:05 CET, Ftmeijer <notifications@github.com> wrote:
>KLopt het dat ik de taalswitch nog niet zie?
>
>Ik zou de taal aanduiding achter de titel vermelden, en ook al in de
>scrollbalk. 
>
>Vening Meinesz (EN)
>Siboga Expeditie (NL) 
>
>
>
>-----------------------------------------------
>Frank Meijer
>Stichting Academisch Erfgoed
>Projectleider
>f.t.meijer@academischerfgoed.nl
><mailto:f.t.meijer@academischerfgoed.nl> 
>06-11060137
>
>www.academischerfgoed.nl <http://www.academischerfgoed.nl/> 
>www.academischecollecties.nl <http://www.academischecollecties.nl/>
>
>
>
>
>> Op 15 mrt. 2015, om 22:20 heeft Simeon Nedkov
><notifications@github.com> het volgende geschreven:
>> 
>> Heb een knop om taal te switchen opgenomen links van hoofdmenu.
>> 
>> Taal switch kan ook als je 'Lees meer' scherm van een expeditie open
>hebt.
>> 
>> Hoe laten we de gebruiker weten dat een expeditie eentalig is?
>> 
>> Ik kan NL/EN achter Start expeditie! knop plaatsen als duiding.
>> 
>> —
>> Reply to this email directly or view it on GitHub
><https://github.com/ndkv/vm/issues/96#issuecomment-81245292>.
>> 
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ndkv/vm/issues/96#issuecomment-81795133

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
